# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d7c17dadaa57bd700de73e229eb8becc6137c6927bf275608b4dbc7b734e7c9779b71f53ba69f674465378be9d8f56bb4f3948fc268f28cfc1e32475e02bc1f

test:
  secret_key_base: b566fe963c7e493f404fd38a0f076571421f08b059c8bd5966646e36d941afb8084bae6db4c297a3f9c63df18cda84182a8871e586ea81327bb88b77dbb323c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
